language: erlang
otp_release:
- 19.3
- 18.3
- 17.5
- R16B03-1
- R16B03
- R15B03-1
- R15B03
before_script:
- wget https://s3.amazonaws.com/rebar3/rebar3
- chmod +x rebar3
env: PATH=$PATH:.
cache:
  directories:
  - $HOME/.cache/rebar3
script:
- rebar3 eunit -c
- rebar3 cover -v
